library(targets)
library(tidyselect)
PKG_VERSION        = utils::packageDescription("DeSurv", fields = "RemoteRef")
GIT_BRANCH         = gert::git_branch()
tar_config_set(store=paste0("store_PKG_VERSION=",PKG_VERSION,"_GIT_BRANCH=",GIT_BRANCH))
# print(targets::tar_config_get("store"))
tar_make()
