#!/bin/bash
# Sync missing target objects from HPC to local store

REMOTE="nur2@longleaf.unc.edu:/work/users/a/y/ayoung31/DeSurv-paper/store_PKG_VERSION=20260107bugfix_GIT_BRANCH=main/objects/"
LOCAL="/home/naimrashid/Downloads/DeSurv-paper/store_PKG_VERSION=20260107bugfix_GIT_BRANCH=main/objects/"

rsync -av --files-from=- "$REMOTE" "$LOCAL" << 'EOF'
desurv_bo_results_tcgacptac
desurv_seed_fits_tcgacptac
fig_bo_heat_tcgacptac
fig_cophenetic_tcgacptac
fig_cutpoint_curves_tcgacptac
fig_desurv_std_correlation_tcgacptac
fig_gene_overlap_heatmap_desurv_alpha0_tcgacptac
fig_gene_overlap_heatmap_desurv_tcgacptac
fig_gene_overlap_heatmap_std_desurvk_tcgacptac
fig_gene_overlap_heatmap_std_elbowk_tcgacptac
fig_hr_forest_tcgacptac
fig_median_survival_desurv_tcgacptac
fig_median_survival_std_desurvk_tcgacptac
fig_residuals_tcgacptac
fig_silhouette_tcgacptac
fig_subtype_overlap_tcgacptac
fig_val_km_dichot_tcgacptac
fig_variation_explained_tcgacptac
fit_std_tcgacptac
sim_figs_by_scenario
tar_data_filtered_tcgacptac
val_cindex_desurv_alpha0_tcgacptac
val_cindex_desurv_tcgacptac
val_cindex_std_desurvk_tcgacptac
val_latent_desurv_tcgacptac
tar_fit_desurv_tcgacptac
fit_std_desurvk_tcgacptac
EOF

# ─────────────────────────────────────────────────────────────────────────────
# Sync results/ directory files (generated by standalone scripts in inst/)
# ─────────────────────────────────────────────────────────────────────────────
REMOTE_BASE="nur2@longleaf.unc.edu:/work/users/a/y/ayoung31/DeSurv-paper/"
LOCAL_BASE="/home/naimrashid/Downloads/DeSurv-paper/"

# results/cv_grid/ — K-sensitivity analysis outputs
# Generated by:
#   Rscript inst/cv_grid_validation_analysis_amber_optimal.R
#   Rscript inst/cv_grid_validation_analysis_allgenes.R
#   Rscript inst/k3_k7_nesting_heatmap.R
#   Rscript inst/create_ksens_rds.R
rsync -av --files-from=- "$REMOTE_BASE" "$LOCAL_BASE" << 'EOF2'
results/cv_grid/adj_p_270_matrix.rds
results/cv_grid/adj_p_all_matrix.rds
results/cv_grid/unadj_p_270_matrix.rds
results/cv_grid/hcor_270_matrix.rds
results/cv_grid/hcor_all_matrix.rds
results/cv_grid/master_rows_270.rds
results/cv_grid/master_rows_all.rds
results/cv_grid/lam300_summary.rds
results/cv_grid/production_summary.rds
results/cv_grid/k3_k7_cor_mat.rds
results/cv_grid/k3_k7_summary.rds
results/cv_grid/cv_grid_cutpoint_summary.csv
results/cv_grid/cv_grid_summary.csv
results/cv_grid/cv_grid_fit_summary.csv
results/cv_grid/cv_grid_val_summary.csv
results/cv_grid/cv_grid_best_alpha.csv
EOF2

# results/nmf_pooled_hr.rds — NMF pooled continuous HR
# Generated by: Rscript inst/compute_nmf_pooled_hr.R [store_path]
rsync -av "${REMOTE_BASE}results/nmf_pooled_hr.rds" "${LOCAL_BASE}results/"
