# Add new entries to run multiple configurations side-by-side.
targets_bo_configs <- function() {
  list(
    # easy = list(
    #     data_mode = "external",
    #     data_loader = "load_data",
    #     train_datasets = c("TCGA_PAAD"),
    #     method_trans_train = "none",
    #     desurv_bo_bounds = list(
    #       k_grid = list(lower = 2L, upper = 8L, type = "integer"),
    #       alpha_grid = list(lower = 0, upper = 1, type = "continuous"),
    #       lambda_grid = list(lower = 1e-3, upper = 1e3, scale = "log10"),
    #       nu_grid = list(lower = 0, upper = 1, type = "continuous")
    #     ),
    #     ngene_config = c(1000),
    #     ntop_config = c(100),
    #     lambdaw_config = c(0),
    #     lambdah_config = c(0),
    #     ninit = 2,
    #     bo_n_init = 4,
    #     bo_n_iter = 4,
    #     bo_candidate_pool = 200,
    #     bo_max_refinements = 0,
    #     bo_tol_gain = 0.002,
    #     bo_plateau = 1,
    #     bo_top_k = 10,
    #     bo_shrink_base = 0.3,
    #     bo_importance_gain = 0.1,
    #     bo_coarse_control = NULL,
    #     bo_refine_control = NULL,
    #     bo_tol = 1e-5,
    #     bo_maxit = 4000,
    #     nfold = 5,
    #     desurv_parallel_grid = TRUE,
    #     desurv_ncores_grid = NULL
    # ),
    tcga = list(
      data_mode = "external",
      data_loader = "load_data",
      train_datasets = c("TCGA_PAAD"),
      method_trans_train = "none",
      desurv_bo_bounds = list(
        k_grid = list(lower = 2L, upper = 10L, type = "integer"),
        alpha_grid = list(lower = 0, upper = 1, type = "continuous"),
        lambda_grid = list(lower = 1e-3, upper = 1e3, scale = "log10"),
        nu_grid = list(lower = 0, upper = 1, type = "continuous")
      ),
      ngene_config = c(3000),
      ntop_config = c(50,300),
      lambdaw_config = c(0),
      lambdah_config = c(0),
      ninit = 30,
      bo_n_init = 20,
      bo_n_iter = 50,
      bo_candidate_pool = 4000,
      bo_max_refinements = 1,
      bo_tol_gain = 0.002,
      bo_plateau = 1,
      bo_top_k = 10,
      bo_shrink_base = 0.3,
      bo_importance_gain = 0.1,
      bo_coarse_control = NULL,
      bo_refine_control = NULL,
      bo_tol = 1e-5,
      bo_maxit = 4000,
      nfold = 5,
      desurv_parallel_grid = TRUE,
      desurv_ncores_grid = 30
    ),
    
    tcgaupper = list(
      data_mode = "external",
      data_loader = "load_data",
      train_datasets = c("TCGA_PAAD"),
      method_trans_train = "none",
      desurv_bo_bounds = list(
        k_grid = list(lower = 2L, upper = 16L, type = "integer"),
        alpha_grid = list(lower = 0, upper = 1, type = "continuous"),
        lambda_grid = list(lower = 1e-3, upper = 1e3, scale = "log10"),
        nu_grid = list(lower = 0, upper = 1, type = "continuous")
      ),
      ngene_config = c(3000),
      ntop_config = c(50,300),
      lambdaw_config = c(0),
      lambdah_config = c(0),
      ninit = 30,
      bo_n_init = 20,
      bo_n_iter = 50,
      bo_candidate_pool = 4000,
      bo_max_refinements = 1,
      bo_tol_gain = 0.002,
      bo_plateau = 1,
      bo_top_k = 10,
      bo_shrink_base = 0.3,
      bo_importance_gain = 0.1,
      bo_coarse_control = NULL,
      bo_refine_control = NULL,
      bo_tol = 1e-5,
      bo_maxit = 4000,
      nfold = 5,
      desurv_parallel_grid = TRUE,
      desurv_ncores_grid = 30
    ),
    
    cptac = list(
      data_mode = "external",
      data_loader = "load_data",
      train_datasets = c("CPTAC"),
      method_trans_train = "none",
      desurv_bo_bounds = list(
        k_grid = list(lower = 2L, upper = 10L, type = "integer"),
        alpha_grid = list(lower = 0, upper = 1, type = "continuous"),
        lambda_grid = list(lower = 1e-3, upper = 1e3, scale = "log10"),
        nu_grid = list(lower = 0, upper = 1, type = "continuous")
      ),
      ngene_config = c(3000),
      ntop_config = c(50,300),
      lambdaw_config = c(0),
      lambdah_config = c(0),
      ninit = 30,
      bo_n_init = 20,
      bo_n_iter = 50,
      bo_candidate_pool = 4000,
      bo_max_refinements = 1,
      bo_tol_gain = 0.002,
      bo_plateau = 1,
      bo_top_k = 10,
      bo_shrink_base = 0.3,
      bo_importance_gain = 0.1,
      bo_coarse_control = NULL,
      bo_refine_control = NULL,
      bo_tol = 1e-5,
      bo_maxit = 4000,
      nfold = 5,
      desurv_parallel_grid = TRUE,
      desurv_ncores_grid = 30
    ),
    
    cptacupper = list(
      data_mode = "external",
      data_loader = "load_data",
      train_datasets = c("CPTAC"),
      method_trans_train = "none",
      desurv_bo_bounds = list(
        k_grid = list(lower = 2L, upper = 16L, type = "integer"),
        alpha_grid = list(lower = 0, upper = 1, type = "continuous"),
        lambda_grid = list(lower = 1e-3, upper = 1e3, scale = "log10"),
        nu_grid = list(lower = 0, upper = 1, type = "continuous")
      ),
      ngene_config = c(3000),
      ntop_config = c(50,300),
      lambdaw_config = c(0),
      lambdah_config = c(0),
      ninit = 30,
      bo_n_init = 20,
      bo_n_iter = 50,
      bo_candidate_pool = 4000,
      bo_max_refinements = 1,
      bo_tol_gain = 0.002,
      bo_plateau = 1,
      bo_top_k = 10,
      bo_shrink_base = 0.3,
      bo_importance_gain = 0.1,
      bo_coarse_control = NULL,
      bo_refine_control = NULL,
      bo_tol = 1e-5,
      bo_maxit = 4000,
      nfold = 5,
      desurv_parallel_grid = TRUE,
      desurv_ncores_grid = 30
    ),
    
    
    moffitt = list(
      data_mode = "external",
      data_loader = "load_data",
      train_datasets = c("Moffitt_GEO_array"),
      method_trans_train = "none",
      desurv_bo_bounds = list(
        k_grid = list(lower = 2L, upper = 10L, type = "integer"),
        alpha_grid = list(lower = 0, upper = 1, type = "continuous"),
        lambda_grid = list(lower = 1e-3, upper = 1e3, scale = "log10"),
        nu_grid = list(lower = 0, upper = 1, type = "continuous")
      ),
      ngene_config = c(3000),
      ntop_config = c(50,300),
      lambdaw_config = c(0),
      lambdah_config = c(0),
      ninit = 30,
      bo_n_init = 20,
      bo_n_iter = 50,
      bo_candidate_pool = 4000,
      bo_max_refinements = 1,
      bo_tol_gain = 0.002,
      bo_plateau = 1,
      bo_top_k = 10,
      bo_shrink_base = 0.3,
      bo_importance_gain = 0.1,
      bo_coarse_control = NULL,
      bo_refine_control = NULL,
      bo_tol = 1e-5,
      bo_maxit = 4000,
      nfold = 5,
      desurv_parallel_grid = TRUE,
      desurv_ncores_grid = 30
    ),

    
    moffittupper = list(
      data_mode = "external",
      data_loader = "load_data",
      train_datasets = c("Moffitt_GEO_array"),
      method_trans_train = "none",
      desurv_bo_bounds = list(
        k_grid = list(lower = 2L, upper = 16L, type = "integer"),
        alpha_grid = list(lower = 0, upper = 1, type = "continuous"),
        lambda_grid = list(lower = 1e-3, upper = 1e3, scale = "log10"),
        nu_grid = list(lower = 0, upper = 1, type = "continuous")
      ),
      ngene_config = c(3000),
      ntop_config = c(50,300),
      lambdaw_config = c(0),
      lambdah_config = c(0),
      ninit = 30,
      bo_n_init = 20,
      bo_n_iter = 50,
      bo_candidate_pool = 4000,
      bo_max_refinements = 1,
      bo_tol_gain = 0.002,
      bo_plateau = 1,
      bo_top_k = 10,
      bo_shrink_base = 0.3,
      bo_importance_gain = 0.1,
      bo_coarse_control = NULL,
      bo_refine_control = NULL,
      bo_tol = 1e-5,
      bo_maxit = 4000,
      nfold = 5,
      desurv_parallel_grid = TRUE,
      desurv_ncores_grid = 30
    ),
    
    tcgarank = list(
      data_mode = "external",
      data_loader = "load_data",
      train_datasets = c("TCGA_PAAD"),
      method_trans_train = "rank",
      desurv_bo_bounds = list(
        k_grid = list(lower = 2L, upper = 10L, type = "integer"),
        alpha_grid = list(lower = 0, upper = 1, type = "continuous"),
        lambda_grid = list(lower = 1e-3, upper = 1e3, scale = "log10"),
        nu_grid = list(lower = 0, upper = 1, type = "continuous")
      ),
      ngene_config = c(3000),
      ntop_config = c(50,300),
      lambdaw_config = c(0),
      lambdah_config = c(0),
      ninit = 30,
      bo_n_init = 20,
      bo_n_iter = 50,
      bo_candidate_pool = 4000,
      bo_max_refinements = 1,
      bo_tol_gain = 0.002,
      bo_plateau = 1,
      bo_top_k = 10,
      bo_shrink_base = 0.3,
      bo_importance_gain = 0.1,
      bo_coarse_control = NULL,
      bo_refine_control = NULL,
      bo_tol = 1e-5,
      bo_maxit = 4000,
      nfold = 5,
      desurv_parallel_grid = TRUE,
      desurv_ncores_grid = 30
    ),

    tcgarankupper = list(
      data_mode = "external",
      data_loader = "load_data",
      train_datasets = c("TCGA_PAAD"),
      method_trans_train = "rank",
      desurv_bo_bounds = list(
        k_grid = list(lower = 2L, upper = 16L, type = "integer"),
        alpha_grid = list(lower = 0, upper = 1, type = "continuous"),
        lambda_grid = list(lower = 1e-3, upper = 1e3, scale = "log10"),
        nu_grid = list(lower = 0, upper = 1, type = "continuous")
      ),
      ngene_config = c(3000),
      ntop_config = c(50,300),
      lambdaw_config = c(0),
      lambdah_config = c(0),
      ninit = 30,
      bo_n_init = 20,
      bo_n_iter = 50,
      bo_candidate_pool = 4000,
      bo_max_refinements = 1,
      bo_tol_gain = 0.002,
      bo_plateau = 1,
      bo_top_k = 10,
      bo_shrink_base = 0.3,
      bo_importance_gain = 0.1,
      bo_coarse_control = NULL,
      bo_refine_control = NULL,
      bo_tol = 1e-5,
      bo_maxit = 4000,
      nfold = 5,
      desurv_parallel_grid = TRUE,
      desurv_ncores_grid = 30
    ),
    
    tcgacptac = list(
      data_mode = "external",
      data_loader = "load_data",
      train_datasets = c("TCGA_PAAD","CPTAC"),
      method_trans_train = "rank",
      desurv_bo_bounds = list(
        k_grid = list(lower = 2L, upper = 10L, type = "integer"),
        alpha_grid = list(lower = 0, upper = 1, type = "continuous"),
        lambda_grid = list(lower = 1e-3, upper = 1e3, scale = "log10"),
        nu_grid = list(lower = 0, upper = 1, type = "continuous")
      ),
      ngene_config = c(3000),
      ntop_config = c(50,300),
      lambdaw_config = c(0),
      lambdah_config = c(0),
      ninit = 30,
      bo_n_init = 20,
      bo_n_iter = 50,
      bo_candidate_pool = 4000,
      bo_max_refinements = 1,
      bo_tol_gain = 0.002,
      bo_plateau = 1,
      bo_top_k = 10,
      bo_shrink_base = 0.3,
      bo_importance_gain = 0.1,
      bo_coarse_control = NULL,
      bo_refine_control = NULL,
      bo_tol = 1e-5,
      bo_maxit = 4000,
      nfold = 5,
      desurv_parallel_grid = TRUE,
      desurv_ncores_grid = 30
    ),

    tcgacptacupper = list(
      data_mode = "external",
      data_loader = "load_data",
      train_datasets = c("TCGA_PAAD","CPTAC"),
      method_trans_train = "rank",
      desurv_bo_bounds = list(
        k_grid = list(lower = 2L, upper = 16L, type = "integer"),
        alpha_grid = list(lower = 0, upper = 1, type = "continuous"),
        lambda_grid = list(lower = 1e-3, upper = 1e3, scale = "log10"),
        nu_grid = list(lower = 0, upper = 1, type = "continuous")
      ),
      ngene_config = c(3000),
      ntop_config = c(50,300),
      lambdaw_config = c(0),
      lambdah_config = c(0),
      ninit = 30,
      bo_n_init = 20,
      bo_n_iter = 50,
      bo_candidate_pool = 4000,
      bo_max_refinements = 1,
      bo_tol_gain = 0.002,
      bo_plateau = 1,
      bo_top_k = 10,
      bo_shrink_base = 0.3,
      bo_importance_gain = 0.1,
      bo_coarse_control = NULL,
      bo_refine_control = NULL,
      bo_tol = 1e-5,
      bo_maxit = 4000,
      nfold = 5,
      desurv_parallel_grid = TRUE,
      desurv_ncores_grid = 30
    ),
    
    # default = list(
    #   data_mode = "external",
    #   data_loader = "load_data",
    #   train_datasets = c("TCGA_PAAD"),
    #   method_trans_train = "rank",
    #   desurv_bo_bounds = list(
    #     k_grid = list(lower = 2L, upper = 10L, type = "integer"),
    #     alpha_grid = list(lower = 0, upper = 1, type = "continuous"),
    #     lambda_grid = list(lower = 1e-3, upper = 1e3, scale = "log10"),
    #     nu_grid = list(lower = 0, upper = 1, type = "continuous")
    #   ),
    #   ngene_config = c(500, 5000),
    #   lambdaw_config = c(0),
    #   lambdah_config = c(0),
    #   ninit = 50,
    #   bo_n_init = 15,
    #   bo_n_iter = 60,
    #   bo_candidate_pool = 4000,
    #   bo_max_refinements = 2,
    #   bo_tol_gain = 0.002,
    #   bo_plateau = 1,
    #   bo_top_k = 10,
    #   bo_shrink_base = 0.3,
    #   bo_importance_gain = 0.1,
    #   bo_coarse_control = NULL,
    #   bo_refine_control = NULL,
    #   bo_tol = 1e-5,
    #   bo_maxit = 4000,
    #   nfold = 5,
    #   desurv_parallel_grid = TRUE,
    #   desurv_ncores_grid = NULL
    # ),
    # bladdereasy = list(
    #   data_mode = "split",
    #   data_loader = "load_data_bladder_vig",
    #   train_datasets = c("Bladder"),
    #   split_raw_files = "data/original/IMVigor210_sampInfo_ex_clinical.rds",
    #   split_train_frac = 0.7,
    #   split_seed = 123,
    #   split_strata_vars = c("event", "dataset"),
    #   method_trans_train = "none",
    #   desurv_bo_bounds = list(
    #     k_grid = list(lower = 2L, upper = 10L, type = "integer"),
    #     alpha_grid = list(lower = 0, upper = 0.95, type = "continuous"),
    #     lambda_grid = list(lower = 1e-3, upper = 1e3, scale = "log10"),
    #     nu_grid = list(lower = 0, upper = 1, type = "continuous")
    #   ),
    #   ngene_config = 1000,#c(500, 5000),
    #   lambdaw_config = c(0),
    #   lambdah_config = c(0),
    #   ninit = 2,
    #   bo_n_init = 4,
    #   bo_n_iter = 4,
    #   bo_candidate_pool = 200,
    #   bo_max_refinements = 0,
    #   bo_tol_gain = 0.002,
    #   bo_plateau = 1,
    #   bo_top_k = 10,
    #   bo_shrink_base = 0.3,
    #   bo_importance_gain = 0.1,
    #   bo_coarse_control = NULL,
    #   bo_refine_control = NULL,
    #   bo_tol = 1e-5,
    #   bo_maxit = 4000,
    #   nfold = 5,
    #   desurv_parallel_grid = TRUE,
    #   desurv_ncores_grid = 2
    # ),

    bladder = list(
      data_mode = "split",
      data_loader = "load_data_bladder_vig",
      train_datasets = c("Bladder"),
      split_raw_files = "data/original/IMVigor210_sampInfo_ex_clinical.rds",
      split_train_frac = 0.7,
      split_seed = 123,
      split_strata_vars = c("event", "dataset"),
      method_trans_train = "none",
      desurv_bo_bounds = list(
        k_grid = list(lower = 2L, upper = 10L, type = "integer"),
        alpha_grid = list(lower = 0, upper = 0.95, type = "continuous"),
        lambda_grid = list(lower = 1e-3, upper = 1e3, scale = "log10"),
        nu_grid = list(lower = 0, upper = 1, type = "continuous")
      ),
      ngene_config = 3000,#c(500, 5000),
      ntop_config = c(50,300),
      lambdaw_config = c(0),
      lambdah_config = c(0),
      ninit = 30,
      bo_n_init = 20,
      bo_n_iter = 50,
      bo_candidate_pool = 4000,
      bo_max_refinements = 1,
      bo_tol_gain = 0.002,
      bo_plateau = 1,
      bo_top_k = 10,
      bo_shrink_base = 0.3,
      bo_importance_gain = 0.1,
      bo_coarse_control = NULL,
      bo_refine_control = NULL,
      bo_tol = 1e-5,
      bo_maxit = 4000,
      nfold = 5,
      desurv_parallel_grid = TRUE,
      desurv_ncores_grid = 30
    ),
    
    bladdermoretrain = list(
      data_mode = "split",
      data_loader = "load_data_bladder_vig",
      train_datasets = c("Bladder"),
      split_raw_files = "data/original/IMVigor210_sampInfo_ex_clinical.rds",
      split_train_frac = 0.8,
      split_seed = 123,
      split_strata_vars = c("event", "dataset"),
      method_trans_train = "none",
      desurv_bo_bounds = list(
        k_grid = list(lower = 2L, upper = 10L, type = "integer"),
        alpha_grid = list(lower = 0, upper = 0.95, type = "continuous"),
        lambda_grid = list(lower = 1e-3, upper = 1e3, scale = "log10"),
        nu_grid = list(lower = 0, upper = 1, type = "continuous")
      ),
      ngene_config = 3000,#c(500, 5000),
      ntop_config = c(50,300),
      lambdaw_config = c(0),
      lambdah_config = c(0),
      ninit = 30,
      bo_n_init = 20,
      bo_n_iter = 50,
      bo_candidate_pool = 4000,
      bo_max_refinements = 1,
      bo_tol_gain = 0.002,
      bo_plateau = 1,
      bo_top_k = 10,
      bo_shrink_base = 0.3,
      bo_importance_gain = 0.1,
      bo_coarse_control = NULL,
      bo_refine_control = NULL,
      bo_tol = 1e-5,
      bo_maxit = 4000,
      nfold = 5,
      desurv_parallel_grid = TRUE,
      desurv_ncores_grid = 30
    ),
    # 
    # pdacspliteasy = list(
    #   data_mode = "split",
    #   data_loader = "load_data_pdac_split",
    #   train_datasets = c(
    #     "TCGA_PAAD",
    #     "CPTAC",
    #     "Dijk",
    #     "Moffitt_GEO_array",
    #     "PACA_AU_array",
    #     "PACA_AU_seq",
    #     "Puleo_array"
    #   ),
    #   split_raw_files = c(
    #     "data/original/TCGA_PAAD.rds",
    #     "data/original/TCGA_PAAD.survival_data.rds",
    #     "data/original/TCGA_PAAD_subtype.csv",
    #     "data/original/CPTAC.rds",
    #     "data/original/CPTAC.survival_data.rds",
    #     "data/original/CPTAC_subtype.csv",
    #     "data/original/Dijk.rds",
    #     "data/original/Dijk.survival_data.rds",
    #     "data/original/Dijk_subtype.csv",
    #     "data/original/Moffitt_GEO_array.rds",
    #     "data/original/Moffitt_GEO_array.survival_data.rds",
    #     "data/original/Moffitt_GEO_array_subtype.csv",
    #     "data/original/PACA_AU_array.rds",
    #     "data/original/PACA_AU_array.survival_data.rds",
    #     "data/original/PACA_AU_array_subtype.csv",
    #     "data/original/PACA_AU_seq.rds",
    #     "data/original/PACA_AU_seq.survival_data.rds",
    #     "data/original/PACA_AU_seq_subtype.csv",
    #     "data/original/Puleo_array.rds",
    #     "data/original/Puleo_array.survival_data.rds",
    #     "data/original/Puleo_array_subtype.csv"
    #   ),
    #   split_train_frac = 0.7,
    #   split_seed = 123,
    #   split_strata_vars = c("event", "dataset"),
    #   method_trans_train = "rank",
    #   desurv_bo_bounds = list(
    #     k_grid = list(lower = 2L, upper = 10L, type = "integer"),
    #     alpha_grid = list(lower = 0, upper = 1, type = "continuous"),
    #     lambda_grid = list(lower = 1e-3, upper = 1e3, scale = "log10"),
    #     nu_grid = list(lower = 0, upper = 1, type = "continuous")
    #   ),
    #   ngene_config = c(1000),
    #   ntop_config = 100,#c(50, 300),
    #   lambdaw_config = c(0),
    #   lambdah_config = c(0),
    #   ninit = 2,
    #   bo_n_init = 4,
    #   bo_n_iter = 4,
    #   bo_candidate_pool = 200,
    #   bo_max_refinements = 0,
    #   bo_tol_gain = 0.002,
    #   bo_plateau = 1,
    #   bo_top_k = 10,
    #   bo_shrink_base = 0.3,
    #   bo_importance_gain = 0.1,
    #   bo_coarse_control = NULL,
    #   bo_refine_control = NULL,
    #   bo_tol = 1e-5,
    #   bo_maxit = 4000,
    #   nfold = 5,
    #   desurv_parallel_grid = TRUE,
    #   desurv_ncores_grid = 2
    # )
    # 

    pdacsplit = list(
      data_mode = "split",
      data_loader = "load_data_pdac_split",
      train_datasets = c(
        "TCGA_PAAD",
        "CPTAC",
        "Dijk",
        "Moffitt_GEO_array",
        "PACA_AU_array",
        "PACA_AU_seq",
        "Puleo_array"
      ),
      split_raw_files = c(
        "data/original/TCGA_PAAD.rds",
        "data/original/TCGA_PAAD.survival_data.rds",
        "data/original/TCGA_PAAD_subtype.csv",
        "data/original/CPTAC.rds",
        "data/original/CPTAC.survival_data.rds",
        "data/original/CPTAC_subtype.csv",
        "data/original/Dijk.rds",
        "data/original/Dijk.survival_data.rds",
        "data/original/Dijk_subtype.csv",
        "data/original/Moffitt_GEO_array.rds",
        "data/original/Moffitt_GEO_array.survival_data.rds",
        "data/original/Moffitt_GEO_array_subtype.csv",
        "data/original/PACA_AU_array.rds",
        "data/original/PACA_AU_array.survival_data.rds",
        "data/original/PACA_AU_array_subtype.csv",
        "data/original/PACA_AU_seq.rds",
        "data/original/PACA_AU_seq.survival_data.rds",
        "data/original/PACA_AU_seq_subtype.csv",
        "data/original/Puleo_array.rds",
        "data/original/Puleo_array.survival_data.rds",
        "data/original/Puleo_array_subtype.csv"
      ),
      split_train_frac = 0.7,
      split_seed = 123,
      split_strata_vars = c("event", "dataset"),
      method_trans_train = "rank",
      desurv_bo_bounds = list(
        k_grid = list(lower = 2L, upper = 10L, type = "integer"),
        alpha_grid = list(lower = 0, upper = 1, type = "continuous"),
        lambda_grid = list(lower = 1e-3, upper = 1e3, scale = "log10"),
        nu_grid = list(lower = 0, upper = 1, type = "continuous")
      ),
      ngene_config = c(3000),
      ntop_config = c(50, 300),
      lambdaw_config = c(0),
      lambdah_config = c(0),
      ninit = 30,
      bo_n_init = 20,
      bo_n_iter = 50,
      bo_candidate_pool = 4000,
      bo_max_refinements = 1,
      bo_tol_gain = 0.002,
      bo_plateau = 1,
      bo_top_k = 10,
      bo_shrink_base = 0.3,
      bo_importance_gain = 0.1,
      bo_coarse_control = NULL,
      bo_refine_control = NULL,
      bo_tol = 1e-5,
      bo_maxit = 4000,
      nfold = 5,
      desurv_parallel_grid = TRUE,
      desurv_ncores_grid = 30
    ),
    
    pdacsplitupper = list(
      data_mode = "split",
      data_loader = "load_data_pdac_split",
      train_datasets = c(
        "TCGA_PAAD",
        "CPTAC",
        "Dijk",
        "Moffitt_GEO_array",
        "PACA_AU_array",
        "PACA_AU_seq",
        "Puleo_array"
      ),
      split_raw_files = c(
        "data/original/TCGA_PAAD.rds",
        "data/original/TCGA_PAAD.survival_data.rds",
        "data/original/TCGA_PAAD_subtype.csv",
        "data/original/CPTAC.rds",
        "data/original/CPTAC.survival_data.rds",
        "data/original/CPTAC_subtype.csv",
        "data/original/Dijk.rds",
        "data/original/Dijk.survival_data.rds",
        "data/original/Dijk_subtype.csv",
        "data/original/Moffitt_GEO_array.rds",
        "data/original/Moffitt_GEO_array.survival_data.rds",
        "data/original/Moffitt_GEO_array_subtype.csv",
        "data/original/PACA_AU_array.rds",
        "data/original/PACA_AU_array.survival_data.rds",
        "data/original/PACA_AU_array_subtype.csv",
        "data/original/PACA_AU_seq.rds",
        "data/original/PACA_AU_seq.survival_data.rds",
        "data/original/PACA_AU_seq_subtype.csv",
        "data/original/Puleo_array.rds",
        "data/original/Puleo_array.survival_data.rds",
        "data/original/Puleo_array_subtype.csv"
      ),
      split_train_frac = 0.7,
      split_seed = 123,
      split_strata_vars = c("event", "dataset"),
      method_trans_train = "rank",
      desurv_bo_bounds = list(
        k_grid = list(lower = 2L, upper = 16L, type = "integer"),
        alpha_grid = list(lower = 0, upper = 1, type = "continuous"),
        lambda_grid = list(lower = 1e-3, upper = 1e3, scale = "log10"),
        nu_grid = list(lower = 0, upper = 1, type = "continuous")
      ),
      ngene_config = c(3000),
      ntop_config = c(50, 300),
      lambdaw_config = c(0),
      lambdah_config = c(0),
      ninit = 30,
      bo_n_init = 20,
      bo_n_iter = 50,
      bo_candidate_pool = 4000,
      bo_max_refinements = 1,
      bo_tol_gain = 0.002,
      bo_plateau = 1,
      bo_top_k = 10,
      bo_shrink_base = 0.3,
      bo_importance_gain = 0.1,
      bo_coarse_control = NULL,
      bo_refine_control = NULL,
      bo_tol = 1e-5,
      bo_maxit = 4000,
      nfold = 5,
      desurv_parallel_grid = TRUE,
      desurv_ncores_grid = 30
    )
    
  )
}

targets_run_configs <- function() {
  list(
    # easy = list(
    #   bo_key = c("easy","bladdereasy","pdacspliteasy"),#,"bladdereasy","pdacspliteasy"
    #   ninit_full = 10,
    #   run_tol = 1e-5,
    #   run_maxit = 4000,
    #   std_nmf_k_grid = 2:12,
    #   std_nmf_nrun = NULL,
    #   coxnet_lambda_grid = c(1e-4, 1e-3, 1e-2, 0.1, 1, 10),
    #   coxnet_alpha_grid = seq(0, 1, by = 0.1)
    # )
    full = list(
      bo_key = c("tcga","cptac","moffitt","tcgarank","tcgacptac","bladder","pdacsplit"),
      ninit_full = 100,
      run_tol = 1e-5,
      run_maxit = 4000,
      std_nmf_k_grid = 2:12,
      std_nmf_nrun = NULL,
      coxnet_lambda_grid = c(1e-4, 1e-3, 1e-2, 0.1, 1, 10),
      coxnet_alpha_grid = seq(0, 1, by = 0.1)
    )
    # bladdereasy = list(
    #   bo_key = "bladdereasy",
    #   ninit_full = 10,
    #   run_tol = 1e-5,
    #   run_maxit = 4000,
    #   std_nmf_k_grid = 2:12,
    #   std_nmf_nrun = NULL,
    #   coxnet_lambda_grid = c(1e-4, 1e-3, 1e-2, 0.1, 1, 10),
    #   coxnet_alpha_grid = seq(0, 1, by = 0.1)
    # )
    # default = list(
    #   bo_key = "default",
    #   ninit_full = 100,
    #   run_tol = 1e-5,
    #   run_maxit = 4000,
    #   std_nmf_k_grid = 2:12,
    #   std_nmf_nrun = NULL,
    #   coxnet_lambda_grid = c(1e-4, 1e-3, 1e-2, 0.1, 1, 10),
    #   coxnet_alpha_grid = seq(0, 1, by = 0.1)
    # ),
    # bladder_default = list(
    #   bo_key = "bladder",
    #   ninit_full = 100,
    #   run_tol = 1e-5,
    #   run_maxit = 4000,
    #   std_nmf_k_grid = 2:12,
    #   std_nmf_nrun = NULL,
    #   coxnet_lambda_grid = c(1e-4, 1e-3, 1e-2, 0.1, 1, 10),
    #   coxnet_alpha_grid = seq(0, 1, by = 0.1)
    # )
  )
}

targets_val_configs <- function() {
  list(
    # easy = list(
    #   run_key = "easy",
    #   mode = "external",
    #   val_datasets = c(
    #     "CPTAC",
    #     "Dijk",
    #     "Moffitt_GEO_array",
    #     "PACA_AU_array",
    #     "PACA_AU_seq",
    #     "Puleo_array"
    #   )
    # )
    
    full = list(
      run_key = "full",
      mode = "external",
      val_datasets = c(
        "CPTAC",
        "Dijk",
        "Moffitt_GEO_array",
        "PACA_AU_array",
        "PACA_AU_seq",
        "Puleo_array"
      )
    )
    # default = list(
    #   run_key = "default",
    #   mode = "external",
    #   val_datasets = c(
    #     "CPTAC",
    #     "Dijk",
    #     "Moffitt_GEO_array",
    #     "PACA_AU_array",
    #     "PACA_AU_seq",
    #     "Puleo_array"
    #   )
    # )
    # bladder_holdout = list(
    #   run_key = "bladder_default",
    #   mode = "train_split",
    #   val_datasets = character(0)
    # )
  )
}
